---
- name: Setting up payment application
  hosts: payment
  become: True
  tasks:
  - name: installing python related applications
    ansible.builtin.package:
      name: '{{ item }}'
    loop:
    - python36
    - gcc
    - python3-devel

  - name: adding user
    ansible.builtin.user:
      name: roboshop

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading payment code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/payment.zip
      path: /tmp

  - name: unziping code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app

  - name: insatlling dependencies
    ansible.builtin.command: pip3.6 install -r requirements.txt
    args:
      chdir: /app

  - name: copying payment.service
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: reloading daemon
    ansible.builtin.systemd_service:
      daemon_reload: yes

  - name: starting and enabling payment service
    ansible.builtin.service:
      name: payment
      state: restarted
      enabled: yes
      