---
- name: Setting up shipping application
  hosts: shipping
  become: True
  tasks:
  - name: insatlling maven application
    ansible.builtin.package:
      name: maven
      state: present

  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop

  
  - name: Creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading shipping app code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp

  - name: Unzipping code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copying shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: reloading daemon
    ansible.builtin.systemd_service:
      daemon_reload: True


  - name: installing mysql-client
    ansible.builtin.package:
      name:mysql
      state: present

  - name: loading data into sql
    ansible.builtin.shell: mysql -h mysql.174a9.online -uroot -pRoboShop@1 < /app/schema/shipping.sql

  - name: Starting and restarting shipping application
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes
      
